src/objects/Exception_Log__c.object
<CustomObject>
    <description>Stores the exception details.</description>
    <fields>
        <fullName>Class_Method_Name__c</fullName>
        <description>Contains the class and method name where the exception raised</description>
        <inlineHelpText>Contains the class and method name where the exception raised</inlineHelpText>
        <label>Class Method Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Details__c</fullName>
        <description>Contains the Stack Trace Details of the exception.</description>
        <inlineHelpText>Contains the Stack Trace Details of the exception.</inlineHelpText>
        <label>Error Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Contains the details of error occured.</description>
        <inlineHelpText>Contains the details of error occured.</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Contains the type of exception thrown.</description>
        <inlineHelpText>Contains the type of exception thrown.</inlineHelpText>
        <label>Exception Type</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Contains the name of the object.</description>
        <inlineHelpText>Contains the name of the object.</inlineHelpText>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>Contains the Record Id for which the error was thrown.</description>
        <inlineHelpText>Contains the Record Id for which the error was thrown.</inlineHelpText>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{0000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExceptionLogUtil.cls
public class ExceptionLogUtil{

    //@future
    public static void createExceptionLog(String errorMessage){
        System.debug('&&& in create Exception log method');
        insert New Exception_Log__c(Error_Message__c = errorMessage);
    }
    
    public static void createExceptionLog(Exception e){
        
        Exception_Log__c eLog = new Exception_Log__c();
        eLog.Error_Message__c = e.getMessage();
        eLog.Error_Details__c = e.getStackTraceString();
        eLog.Exception_Type__c = e.getTypeName();
        
        insert eLog;
    }
    
    public static void createExceptionLogs(Database.SaveResult[] saveResults, List<SObject> records, String ClassMethodName){
    
        List<Exception_Log__c> excLogList = new List<Exception_Log__c>();
        String objectApiName;
        if(!records.isEmpty()){
            String objectToken = String.valueOf(records[0].getSObjectType());
            Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
            objectApiName = String.valueOf(schemaMap.get(objectToken));
        }
        for(Integer i=0; i<saveResults.size(); i++){
            if(!saveResults[i].success){
                Exception_Log__c eLog = new Exception_Log__c();
                eLog.Object_Name__c = objectApiName;
                eLog.Record_Id__c = records[i].Id;
                eLog.Class_Method_Name__c = ClassMethodName;
                eLog.Exception_Type__c = 'System.DMLException';
                eLog.Error_Message__c = '';
                for(Database.Error err : saveResults[i].getErrors()) {
                    eLog.Error_Message__c += err.getStatusCode() +' : '+err.getMessage();
                }
                excLogList.add(eLog);
            }
        }
        Database.insert(excLogList, false);
    }
    
}