src/objects/Exception_Log__c.object
<CustomObject>
    <description>Stores the exception details.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Contains the details of error occured.</description>
        <inlineHelpText>Contains the details of error occured.</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{0000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDevOrg/src/classes/ExceptionCreationBatch.cls
global class ExceptionCreationBatch implements Database.Batchable<SObject>{

    global Database.QueryLocator start(Database.BatchableContext bc){
    
        return Database.getQueryLocator('select id from Account limit 5');
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope){
    
        insert new Exception_Log__c(Error_Message__c = 'Testing Exception creation');
    }
    
    global void finish(Database.BatchableContext bc){
    
        
    }
}