src/objects/Exception_Log__c.object
<CustomObject>
    <description>Stores the exception details.</description>
    <fields>
        <fullName>Error_Details__c</fullName>
        <description>Contains the Stack Trace Details of the exception.</description>
        <inlineHelpText>Contains the Stack Trace Details of the exception.</inlineHelpText>
        <label>Error Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>Contains the details of error occured.</description>
        <inlineHelpText>Contains the details of error occured.</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <description>Contains the name of the object.</description>
        <inlineHelpText>Contains the name of the object.</inlineHelpText>
        <label>Object Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <description>Contains the Record Id for which the error was thrown.</description>
        <inlineHelpText>Contains the Record Id for which the error was thrown.</inlineHelpText>
        <label>Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{0000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExceptionLogUtilTest.cls
@isTest
Public class ExceptionLogUtilTest{

    public static testmethod void testExceptionLogsCreation(){
        
        // Using Exception Log records to generate the errors because this object do not have any mandatory fields. We can use any object for insertion.
        List<Exception_Log__c> insertList = new List<Exception_Log__c>();
        List<Exception_Log__c> excLogList = new List<Exception_Log__c>();
        for(Integer i=0; i<5; i++){
            insertList.add(new Exception_Log__c());
        }    
        insert insertList;
        Database.saveResult[] saveResults = Database.insert(insertList, false);
        ExceptionLogUtil.createExceptionLogs(saveResults, insertList, 'TestClass');
        excLogList = [Select id, Object_Name__c, Record_Id__c from Exception_Log__c where Object_Name__c = 'Exception_Log__c']; 
        System.assert(excLogList.size()==5);
        System.assert(excLogList[0].Object_Name__c == 'Exception_Log__c');
        System.assert(excLogList[0].Record_Id__c != null);
    }
    
    public static testmethod void testExceptionLogCreation(){
        
        List<Exception_Log__c> excLogList = new List<Exception_Log__c>();
        try{
            List<Exception_Log__c> insertList = new List<Exception_Log__c>();
            String name = insertList[0].Name;
        }
        Catch(Exception e){
            ExceptionLogUtil.createExceptionLog(e);
            excLogList = [Select id, Error_Message__c, Error_Details__c from Exception_Log__c];
            System.assert(excLogList.size()>0);
            System.assert(excLogList[0].Error_Message__c != null);
            System.assert(excLogList[0].Error_Details__c != null);
        }
    }
}