src/objects/PNMSite__c.object
<CustomObject>
    <label>PNM Site</label>
    <nameField>
        <label>PNM Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PNM Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDevOrg/src/objects/Pre_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PreEnrollment</relationshipLabel>
        <relationshipName>PreEnrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PNMSite__c</fullName>
        <label>PNM Site</label>
        <referenceTo>PNMSite__c</referenceTo>
        <relationshipLabel>PreEnrollment</relationshipLabel>
        <relationshipName>PreEnrollments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProviderName__c</fullName>
        <label>Provider Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <label>Pre Enrollment</label>
    <nameField>
        <label>Pre Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PreEnrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MyDevOrg/src/objects/SiteLocation__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Site Locations</relationshipLabel>
        <relationshipName>Site_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PNMSite__c</fullName>
        <label>PNM Site</label>
        <referenceTo>PNMSite__c</referenceTo>
        <relationshipLabel>Site Locations</relationshipLabel>
        <relationshipName>Site_Locations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Site Location</label>
    <nameField>
        <label>Site Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PreEnrollmentUtil.cls
public class PreEnrollmentUtil {
    Public static void updateProviderName(list<Pre_Enrollment__c> newPreEnrList){
       	Map<id,Pre_Enrollment__c> preEnrMap = new Map<id, Pre_Enrollment__c>();
        set<id> pnmSiteSet = new set<id>();
        Map<id,PNMSite__c> pnmSiteMap;
        for(Pre_Enrollment__c pe: newPreEnrList){
            if( pe.PNMSite__c<>null ){
                pnmSiteSet.add(pe.PNMSite__c);
            }
        }
        pnmSiteMap = new Map<id, PNMSite__c>([select id, (select id,contact__r.name from Site_Locations__r where contact__r.name<>null) from PNMSite__c where id in :pnmSiteset]);
        for(Pre_Enrollment__c pe: newPreEnrList){
            if(pnmsitemap.containsKey(pe.PNMSite__c) && pnmSiteMap.get(pe.PNMSite__c).Site_Locations__r.size() == 1){
                pe.ProviderName__c = pnmSiteMap.get(pe.PNMSite__c).Site_Locations__r.get(0).Contact__r.name;
            }
            else{
                pe.ProviderName__c = '';
            }
        }
    }
}