src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/uriRedirectJavaScript.cls
public class uriRedirectJavaScript {
    
    public String targetPage{get;set;}
    public Position__c position{get;set;}
    public String type{get;set;}
    public Id positionId{get;set;}
    
    public uriRedirectJavaScript(ApexPages.StandardController controller) {
        this.position = (Position__c)controller.getRecord();
        this.position = [select id,type__c from Position__c where id = :position.Id];
        type = position.Type__c;
        positionId = position.Id;
    }

}