MyDevOrg/src/objects/Defect__c.object
<CustomObject>
    <fields>
        <fullName>Defect_Name__c</fullName>
        <label>Defect Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>Defects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Arithmetic Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logic Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syntax Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Threading Programming Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interfacing Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Defect</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Defect Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>p-{0000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDevOrg/src/classes/DefectController.cls
public with sharing class DefectController {
       public list<defect__c> defectList { get; set; }
    
    public boolean lrender{get;set;}
    public boolean mreneder{get;set;}
    public boolean hrender{get;set;}
public list<defect__c> lowList { get; set; }
public list<defect__c> mediumList { get; set; }
public list<defect__c> highList { get; set; }


        public string projectnumber{get;set;}
public string stype{set;get;}
public DefectController()
{
}
public list<Selectoption> getProjs(){
  list<selectoption> options=new list<selectoption>();
  options.add(new selectoption('','--None--'));
    
    for(project__c p:[select id,Name from project__c where phase__c='Testing'])    
    {
 options.add(new selectoption(p.id,p.name))       ;
    }
    return options;    
}

public pagereference deflist(){
  
defectList=new list<defect__C>();
defectList=[Select d.Type__c, d.Severity__c,d.Name, d.project__c,d.Description__c, d.Defect_Name__c, d.CreatedDate,d.project__r.project_name__C, d.CreatedById From Defect__c d where d.project__c=:projectnumber  ];

lowList=new list<defect__c>();
mediumList=new list<defect__c>();
highList=new list<defect__c>();

for(defect__c d:defectList){
if(d.severity__c=='Low')
lowList.add(d);
if(d.severity__c=='Medium')
mediumList.add(d);
if(d.severity__c=='High')
highList.add(d);
}
if(!lowList.isempty())
lrender=true;
else lrender=false;
if(!mediumList.isempty())
mreneder=true;
else mreneder=false;
if(!highList.isempty())
hrender=true;
else hrender=false;
return null;
}
}